### ISSUE TITLE
typedef gets formatted with hanging indent

### ISSUE THREAD

**Issue by The-Compiler** [markw65/prettier-plugin-monkeyc#1]
Code such as

```
typedef PointDict as {
    :x as Number,
    :y as Number,
};
```

gets reformatted as:

```
typedef PointDict as {
        :x as Number,
        :y as Number,
    };
```

which seems somewhat odd to me. Is that intended?

PS: Thanks a lot for the Prettier plugin and VS Code extension! I only started it using now after the initial syntax issues I had, but it seems to be a big help in writing Monkey C code!

**Comment by markw65** [comment]
Should be fixed in v2.0.30 of the vscode extension.
