### ISSUE TITLE
Unexpected token error from command line

### ISSUE THREAD

**Issue by cosmanovich** [markw65/prettier-plugin-monkeyc#2]
I want to format my files from the command line with the following command:
```
...:~/Projects/Hassio Garmin/Hassio connect/connect-app$ npx prettier "source/WindowBlindActionView.mc" --write
```
But I keep getting the following error:
```
...:~/Projects/Hassio Garmin/Hassio connect/connect-app$ npx prettier "source/WindowBlindActionView.mc" --write
[error] Unexpected token '.'
```

I get the same result when I install the npm package globally.
Maybe it is important to note that I'm running on Ubuntu and formatting on save in VS Code with the extension works.
Any suggestions on how to fix this?

**Comment by markw65** [comment]
Not sure - it works for me, even on ubuntu (I have a number of tests that do exactly this).

Also, that doesn't look like an error the plugin might raise - it tends to report things like `SyntaxError: Expected "(", "[", "class", "const", "enum", "function", "hidden", "import", "module", "private", "protected", "public", "static", "typedef", "using", "var", comment, end of input, end of line, or whitespace but "." found`

Given that, and the fact that it works inside vs using the extension, I think it must be a setup issue.
 - Is prettier installed in the same project? It should be automatically installed when you install the monkeyc plugin, but its a peer dependency, so I think there are some circumstances where its not
 - does prettier work with other file types? eg can you format a .js file from the command line?
 - what version of prettier and the plugin do you have? npm list will tell you. I just tried on ubuntu with the latest plugin, and both prettier 2.7.1 (which is what I happened to have installed) and then upgraded to 2.8.7, and it worked with both.
 - does it work if you explicitly invoke the plugin: `npx prettier --plugin node_modules/@markw65/prettier-plugin-monkeyc/build/prettier-plugin-monkeyc.cjs path-to-file.mc`

**Comment by cosmanovich** [comment]
Since everything was working for you on Ubuntu I looked at my setup again and I saw that an older version of nodejs was used (I think it was version 14). I updated my node to version 18 and now everything is working. 

Sorry for the inconvenience and thank you for your help.
